#!/bin/bash
TMPFILE="mktemp --tmpdir athena-run-temp-XXXXXX.ath"
echo "(load \""$1"\")" >> "$TMPFILE"
echo "quit" >> "$TMPFILE"
echo " " >> "$TMPFILE"
time ${ATHENA_HOME}/athena < "$TMPFILE"
rm "$TMPFILE"
