#!/bin/bash
TMPDIR=`dirname $(mktemp -u)`
rm "$TMPDIR"/athena-run-temp.ath
echo "(load \""$1"\")" >> "$TMPDIR"/athena-run-temp.ath
echo "quit" >> "$TMPDIR"/athena-run-temp.ath
echo " " >> "$TMPDIR"/athena-run-temp.ath
time ${ATHENA_HOME}/athena < "$TMPDIR"/athena-run-temp.ath



