name: ci_regression_tests

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build-and-test-linux:
    name: Build and test on linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pre-requisites
        run: |
          sudo apt-get -y update
          sudo apt-get install -y make mlton minisat spass cvc4 smlnj ml-yacc ml-ulex
      - name: Build
        env:
          prefix: ${{ runner.temp }}
        run: |
          make smlnj
      - name: Regression tests
        run: |
          make test


