name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]



jobs:

  generate-release:
    name: Generate release & tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: version
        run: echo "::set-output name=version::$(cat version.txt)"
        shell: bash
        id: version
      - name: create-release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: Athena ${{ steps.version.outputs.version }}
          tag_name: ${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-linux:
    name: Release binaries and supporting files (Linux)
    runs-on: ubuntu-latest
    needs: generate-release
    steps:
      - uses: actions/checkout@v2
      - name: Install pre-requisites
        run: |
          sudo apt-get -y update
          sudo apt-get install -y make mlton minisat spass cvc4 smlnj ml-yacc ml-ulex
      - name: Build
        run: | 
          make smlnj packages

      - name: Upload artifacts
        uses: actions/upload-release-asset@v1
        id: upload-artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.generate-release.steps.create_release.outputs.upload_url }}
          asset_path: ./packages/athena-linux-${{ needs.generate-release.steps.version.outputs.version }}.zip
          asset_name: athena-linux-${{ needs.generate-release.steps.version.outputs.version }}.zip
          asset_content_type: application/zip


  release-macos:
    name: Release binaries and supporting files (macos)
    runs-on: macos-latest
    needs: generate-release
    steps:
      - uses: actions/checkout@v2
      - name: Install pre-requisites
        run: |
          brew install mlton smlnj
      - name: Build
        run: | 
          make packages
      - name: version
        run: |
          echo "::set-output name=version::$(cat version.txt)"
        id: version
      - name: Upload artifacts
        uses: actions/upload-release-asset@v1
        id: upload-artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.generate-release.steps.create_release.outputs.upload_url }}
          asset_path: ./packages/athena-darwin-${{ needs.generate-release.steps.version.outputs.version }}.zip
          asset_name: athena-darwin-${{ needs.generate-release.steps.version.outputs.version }}.zip
          asset_content_type: application/zip